---
title: "Visualize Tweets"
---

```{r setup, include = FALSE}
library("rtweet")
library("stringr")
library("tidyverse")
library("jsonlite")
library("rjson")
library("maps")
```

# Visualization

```{r, generate-map, message = FALSE, warning = FALSE, results = 'hide'}
# Creating a data frame with map data and setting colour coding and languages to highlight
map.data <- map_data("world")
colours <- c("es" = "red","pt" = "blue", "it" = "yellow2", "en" = "purple","tl" = "green")
colour_labels <- c("es" = "Spanish", "pt" = "Portuguese", "it" = "Italian", "tl" = "Tagalog", "en" = "English")
tweets_top_langs <- filter(tweets_clean, lang %in% c("es", "pt", "it", "en", "tl"))

# Plotting
# Map base
ggplot(map.data) + 
geom_map(aes(map_id = region), map = map.data, fill = "grey90", 
color = "grey50", size = 0.25) + expand_limits(x = map.data$long, y = map.data$lat) + 
# Limits for x and y axis using south america coordinates used to stream tweets
scale_x_continuous(limits=c(-80, -34)) + scale_y_continuous(limits = c(-56, 13)) +
# Add dot for each tweet
geom_point(data = tweets_top_langs, aes(x = lng, y = lat,colour = factor(lang)), size = 1,
alpha = 1/5) + 
coord_fixed(ratio = 1.3) +
scale_colour_manual(values = colours, name = "Tweet Language", labels = colour_labels) +
# Making adjustments to legend colour, size, position
guides(color = guide_legend(override.aes = list(alpha = 1))) +
theme(legend.position = c(1, 0.9),
legend.key.size = unit(.4, "cm"),
rect = element_rect(fill = "transparent"), 
# Removing unnecessary graph elements
axis.line = element_blank(), 
axis.text = element_blank(), 
axis.ticks = element_blank(), 
axis.title = element_blank(),
axis.title.x=element_blank(),
axis.title.y=element_blank(),
panel.background = element_blank(), 
panel.border = element_blank(), 
panel.grid.major = element_blank(), 
panel.grid.minor = element_blank(), 
plot.background = element_blank())

#Save plot in graphics folder
#ggsave(plot = last_plot(), filename = "graphics/tweets_map.pdf", width = 6, height = 9)
```

